name: Push to ECR
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup node 12
      uses: actions/setup-node@v2-beta
      with:
        node-version: '12.x'

    - name: Cache node modules
      id: cache-node
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install dependencies
      if: steps.cache-node.outputs.cache-hit != 'true'
      run: |
        npm install --silent
    - name: Build site
      run:  npm run build

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1


    - name: Login to Container Registry
      uses: docker/login-action@v1 
      with:
        registry: 377117578606.dkr.ecr.ap-southeast-2.amazonaws.com
        username: ${{ secrets.AWS_ACCESS_KEY_ID }}
        password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: 377117578606.dkr.ecr.ap-southeast-2.amazonaws.com/popular-repos:${{ github.event.pull_request.head.sha || github.sha }}
        cache-from: type=registry,ref=377117578606.dkr.ecr.ap-southeast-2.amazonaws.com/popular-repos:latest
        cache-to: type=inline
